name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: '>=3.13'
      - name: setup redneck
        run: pip install redneck
      - name: build
        run: |
            redneck build full -o .redneck/build/Universalis.mrpack -b all
            redneck build base -o .redneck/build/server.mrpack
      - name: optimize archive compression
        run: |
          sudo apt-get update && sudo apt-get install -y advancecomp
          advzip --recompress --shrink-insane .redneck/build/Universalis.mrpack
          advzip --recompress --shrink-insane .redneck/build/server.mrpack
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: .redneck/build/
