name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v7
      - name: setup python
        uses: actions/setup-python@v7
        with:
          python-version: '>=3.13'
      - name: setup redneck
        run: pip install redneck
      - name: build
        run: |
            redneck build full
            redneck build server
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: .redneck/build/
